## 大作业
本次练习使用 鸢尾属植物数据集.\iris.data，在这个数据集中，包括了三类不同的鸢尾属植物：Iris Setosa，Iris Versicolour，Iris Virginica。每类收集了50个样本，因此这个数据集一共包含了150个样本。

sepallength：萼片长度
sepalwidth：萼片宽度
petallength：花瓣长度
petalwidth：花瓣宽度
以上四个特征的单位都是厘米（cm）。

### 1. 导入鸢尾属植物数据集，保持文本不变。

* 【知识点：输入和输出】

* 如何导入存在数字和文本的数据集？

In [10]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"  
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']  
dataset = pd.read_csv(url, names=names)
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

### 2. 求出鸢尾属植物萼片长度的平均值、中位数和标准差（第1列，sepallength）

* 【知识点：统计相关】
* 如何计算numpy数组的均值，中位数，标准差？

In [12]:
dataset.describe()

sepal-length  sepal-width  petal-length  petal-width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

### 3. 创建一种标准化形式的鸢尾属植物萼片长度，其值正好介于0和1之间，这样最小值为0，最大值为1（第1列，sepallength）。

* 【知识点：统计相关】
* 如何标准化数组？

In [19]:
from sklearn.preprocessing import MinMaxScaler
scaled_sepal_len = MinMaxScaler().fit_transform(dataset[['sepal-length']])
scaled_sepal_len[:10]

array([[0.22222222],
       [0.16666667],
       [0.11111111],
       [0.08333333],
       [0.19444444],
       [0.30555556],
       [0.08333333],
       [0.19444444],
       [0.02777778],
       [0.16666667]])

### 4. 找到鸢尾属植物萼片长度的第5和第95百分位数（第1列，sepallength）。

* 【知识点：统计相关】
* 如何找到numpy数组的百分位数？

In [21]:
import numpy as np
np.percentile(dataset['sepal-length'],[5,95])

array([4.6  , 7.255])

### 5. 把iris_data数据集中的20个随机位置修改为np.nan值。

* 【知识点：随机抽样】
* 如何在数组中的随机位置修改值？

In [30]:
np.random.seed(20201201)
#产生20个随机位子
rand = np.random.randint(0, dataset.shape[0]*4, size=20, dtype='l')
# 转为行列坐标
r= rand//4
c = rand % 4

ds_test = dataset.copy()

# 设置为未知
for i in range(20):
    ds_test.iloc[r[i],c[i]] = np.nan
# 做基本测试
ds_test.head()

sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          NaN  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

### 6. 在iris_data的sepallength中查找缺失值的个数和位置（第1列）。

* 【知识点：逻辑函数、搜索】
* 如何在numpy数组中找到缺失值的位置？

In [39]:
ds_test['sepal-length'].isnull().any()
# 缺失值个数
sum(ds_test['sepal-length'].isnull())
# 具体位置
ds_test['sepal-length'][ds_test['sepal-length'].isnull().values==True].index.tolist()
#data[columname][data[columname].isnull().values==True].index.tolist()

[10, 36]

### 7. 筛选具有 sepallength（第1列）< 5.0 并且 petallength（第3列）> 1.5 的 iris_data行。

* 【知识点：搜索】
* 如何根据两个或多个条件筛选numpy数组？

In [41]:
ds_filter = dataset[(dataset['sepal-length']<5.0) &(dataset['petal-length']>1.5)]
ds_filter.head()

sepal-length  sepal-width  petal-length  petal-width            class
11           4.8          3.4           1.6          0.2      Iris-setosa
24           4.8          3.4           1.9          0.2      Iris-setosa
29           4.7          3.2           1.6          0.2      Iris-setosa
30           4.8          3.1           1.6          0.2      Iris-setosa
57           4.9          2.4           3.3          1.0  Iris-versicolor


### 8. 选择没有任何 nan 值的 iris_data行。

* 【知识点：逻辑函数、搜索】
* 如何从numpy数组中删除包含缺失值的行？

In [52]:
t = ds_test.isnull().any(axis = 1)
rows = t[t==False].index.tolist()
print(len(rows))
print(rows)
data_selected = ds_test.iloc[rows]
data_selected.shape

130
[1, 2, 3, 4, 5, 7, 8, 9, 11, 14, 15, 16, 17, 19, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 33, 34, 35, 37, 38, 39, 42, 45, 46, 47, 48, 50, 51, 52, 53, 54, 55, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]


(130, 5)


### 9. 计算 iris_data 中sepalLength（第1列）和petalLength（第3列）之间的相关系数。

* 【知识点：统计相关】
* 如何计算numpy数组两列之间的相关系数？

In [53]:
np.corrcoef(dataset['sepal-length'],dataset['petal-length'])

array([[1.        , 0.87175416],
       [0.87175416, 1.        ]])

### 10. 找出iris_data是否有任何缺失值。

* 【知识点：逻辑函数】
* 如何查找给定数组是否具有空值？

In [56]:
sum(ds_test.isnull().any())>0

True

### 11. 在numpy数组中将所有出现的nan替换为0。

* 【知识点：逻辑函数】
* 如何在numpy数组中用0替换所有缺失值？

In [60]:
ds1 = ds_test.copy()
ds1.fillna(0,inplace=True)
ds1.isnull().any()

sepal-length    False
sepal-width     False
petal-length    False
petal-width     False
class           False
dtype: bool

### 12. 找出鸢尾属植物物种中的唯一值和唯一值出现的数量。

* 【知识点：数组操作】
* 如何在numpy数组中查找唯一值的计数？

In [66]:
# 种类唯一值
dataset['class'].unique()
# 各种类数量
dataset.groupby(['class'])['sepal-length'].count()#

class
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: sepal-length, dtype: int64

### 13. 将 iris_data 的花瓣长度（第3列）以形成分类变量的形式显示。
定义：Less than 3 --> 'small'；3-5 --> 'medium'；'>=5 --> 'large'。
* 【知识点：统计相关】
* 如何将数字转换为分类（文本）数组？

In [73]:
# 分段数组
petal_length_bin = np.digitize(dataset.iloc[:,2], [0, 3, 5],right=True)
# 转成文字
mapper = {1:'small',2:'medium',3:'large'}
petal_length_txt = [mapper[x] for x in petal_length_bin]
petal_length_txt

['small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medi

### 14. 在 iris_data 中创建一个新列:
其中 volume 是 (pi x petallength x sepallength ^ 2）/ 3。

* 【知识点：数组操作】
* 如何从numpy数组的现有列创建新列？

In [78]:
import math
dataset['new'] = (dataset['petal-length']*pow(dataset['sepal-length'],2)*math.pi)/3
dataset['new'][:10]

0    38.132652
1    35.200498
2    30.072372
3    33.238050
4    36.651914
5    51.911677
6    31.022180
7    39.269908
8    28.383242
9    37.714820
Name: new, dtype: float64

### 15. 随机抽鸢尾属植物的种类，
使得Iris-setosa的数量是Iris-versicolor和Iris-virginica数量的两倍。

* 【知识点：随机抽样】
* 如何在numpy中进行概率抽样？

In [83]:
# 按维度一定比例分层抽样
np.random.seed(20201201)
#产生x个setosa:x<50
n = 10
col_class = dataset['class']
setosa_pos = col_class[col_class=='Iris-setosa'].index.tolist()
print(setosa_pos)
rand1 = np.random.choice(setosa_pos,n )
print(rand1)
rand2 = np.random.choice(col_class[col_class=='Iris-versicolor'].index.tolist(),n//2)
rand3 = np.random.choice(col_class[col_class=='Iris-virginica'].index.tolist(),n//2)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
[ 9 43 27 33 42 38 10  3 35 40]
[66 74 67 77 92] [132 137 137 131 146]


In [92]:
samples = dataset.iloc[list(rand1)+list(rand2)+list(rand3)]


sepal-length  sepal-width  petal-length  petal-width            class  \
9             4.9          3.1           1.5          0.1      Iris-setosa   
43            5.0          3.5           1.6          0.6      Iris-setosa   
27            5.2          3.5           1.5          0.2      Iris-setosa   
33            5.5          4.2           1.4          0.2      Iris-setosa   
42            4.4          3.2           1.3          0.2      Iris-setosa   
38            4.4          3.0           1.3          0.2      Iris-setosa   
10            5.4          3.7           1.5          0.2      Iris-setosa   
3             4.6          3.1           1.5          0.2      Iris-setosa   
35            5.0          3.2           1.2          0.2      Iris-setosa   
40            5.0          3.5           1.3          0.3      Iris-setosa   
66            5.6          3.0           4.5          1.5  Iris-versicolor   
74            6.4          2.9           4.3          1.3  Iris-versicolor   
67            5.8          2.7           4.1          1.0  Iris-versicolor   
77            6.7          3.0           5.0          1.7  Iris-versicolor   
92            5.8          2.6           4.0          1.2  Iris-versicolor   
132           6.4          2.8           5.6          2.2   Iris-virginica   
137           6.4          3.1           5.5          1.8   Iris-virginica   
137           6.4          3.1           5.5          1.8   Iris-virginica   
131           7.9          3.8           6.4          2.0   Iris-virginica   
146           6.3          2.5           5.0          1.9   Iris-virginica   

            new  
9     37.714820  
43    41.887902  
27    42.474333  
33    44.348816  
42    26.355868  
38    26.355868  
10    45.804421  
3     33.238050  
35    31.415927  
40    34.033920  
66   147.780518  
74   184.440810  
67   144.433675  
77   235.043490  
92   140.910902  
132  240.201986  
137  235.912664  
137  235.912664  
131  418.275835  
146  207.816354

### 16. 根据 sepallength 列对数据集进行排序。

* 【知识点：排序】
* 如何按列对2D数组进行排序？

In [103]:
#x = np.sort(dataset,order='sepal-length')
arr = dataset.to_numpy()
sorted_array = arr[np.argsort(arr[:, 0])]
sorted_array[:10]

array([[4.3, 3.0, 1.1, 0.1, 'Iris-setosa', 21.2989509937876],
       [4.4, 3.2, 1.3, 0.2, 'Iris-setosa', 26.355867968515977],
       [4.4, 3.0, 1.3, 0.2, 'Iris-setosa', 26.355867968515977],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa', 28.383242427632585],
       [4.5, 2.3, 1.3, 0.3, 'Iris-setosa', 27.567475535250434],
       [4.6, 3.6, 1.0, 0.2, 'Iris-setosa', 22.158700183320004],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa', 33.238050274980004],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa', 31.022180256648],
       [4.6, 3.2, 1.4, 0.2, 'Iris-setosa', 31.022180256648],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa', 30.072372077712703]],
      dtype=object)

### 17. 在鸢尾属植物数据集中找到最常见的花瓣长度值（第3列）。

* 【知识点：数组操作】
* 如何在numpy数组中找出出现次数最多的值？

In [115]:

from scipy import stats

stats.mode(dataset['petal-length'])[0][0]


1.5


### 18. 在鸢尾花数据集的 petalwidth（第4列）中查找第一次出现的值大于1.0的位置。

* 【知识点：搜索】
* 如何找到第一次出现大于给定值的位置？

In [117]:
dataset[dataset['petal-width']>1].index.tolist()[0]

50